In [17]:
import pandas as pd

In [18]:
pd.read_csv("india_non-virus-deaths.csv")

,DB_LASTUPDATED_SET,S. No,Incident Location,District,State/UT,Date of incident,No. of deaths,Reason of death,Source,Date of publication,Link,Category,Name(s) and age,Occupation\nCategory
0,SET_JUNE-13,1.0,Agra,Agra,Uttar Pradesh,"March 28,2020",1.0,"Exhaustion, Migration",Times of India,"March 28,2020",https://m.timesofindia.com/city/agra/food-deli...,DarkGreen,Ranveer Singh (39),migrant worker- restaurant
1,SET_JUNE-13,2.0,Pandesara,Surat,Gujarat,"March 27, 2020",1.0,"Exhaustion, Lockdown",Indian Express,"March 28, 2020",https://indianexpress.com/article/india/india-...,DarkGreen,Gangaram(62),unspecified
2,SET_JUNE-13,3.0,Jaipur,Jaipur,Rajasthan,"March 29, 2020",1.0,"Walking, exhaustion, got sick",Amar Ujala,"March 30, 2020",https://www.amarujala.com/uttar-pradesh/kanpur...,DarkGreen,Sher Singh,migrant worker
3,SET_JUNE-13,4.0,Secunderabad,Secunderabad,Telangana,"April 1, 2020",1.0,"Exhaustion, Migration",NDTV,"April 2, 2020",https://www.ndtv.com/india-news/coronavirus-co...,DarkGreen,Logesh Balasubramani (23),migrant worker
4,SET_JUNE-13,5.0,Mountainous peak over Jawahar Tunnel,Anantnag,Jammu and Kashmir,"March 31, 2020",3.0,"Buried under snow, Roadblock, Migration",The Indian Express,"April 2, 2020",https://indianexpress.com/article/india/jammu-...,DarkGreen,"Zubair Ahmed (18), Riyaz Ahmed (19), Ghulam Mo...",migrant worker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,SET_JUNE-13,35.0,Kalenda,Mahasamund,Chhattisgarh,"June 2, 2020",1.0,"death at quarantine centre, unclear, death in ...",Patrika,"June 4, 2020",https://www.patrika.com/mahasamund-news/mother...,MediumPurple,unspecified,unspecified
697,SET_JUNE-13,36.0,Gohrapadar,Gariaband,Chhattisgarh,"June 6, 2020",1.0,"suicide in quarantine centre, unclear",Bhaskar,"June 7, 2020",https://www.bhaskar.com/local/chhattisgarh/new...,MediumPurple,unspecified (20),migrant worker
698,SET_JUNE-13,37.0,Jayarampur,Balasore,Odisha,"June 30, 2020",1.0,"suicide in quarantine centre, unclear",Sambad,"July 1, 2020",https://sambadenglish.com/woman-found-hanging-...,MediumPurple,unspecified (50),migrant worker
699,SET_JUNE-13,38.0,Dehradun,Dehradun,Uttarakhand,"June 12, 2020",1.0,"suicide in quarantine centre, unclear",Deccan Herald,"June 12, 2020",https://www.deccanherald.com/national/north-an...,MediumPurple,unspecified (19),migrant worker
700,SET_JUNE-13,39.0,NaN,NaN,Chhattisgarh,May 21-June 4 2020,11.0,"deaths in quarantine centres, multiple reasons",CG Khabar,"June 9, 2020",https://docs.google.com/document/d/1zZ0IftQMCf...,MediumPurple,NaN,NaN

In [19]:
#1. check types and nulls
pd.read_csv("india_non-virus-deaths.csv").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DB_LASTUPDATED_SET   699 non-null    object
 1   S. No                700 non-null    float64
 2   Incident Location    556 non-null    object
 3   District             672 non-null    object
 4   State/UT             698 non-null    object
 5   Date of incident     694 non-null    object
 6   No. of deaths        700 non-null    float64
 7   Reason of death      700 non-null    object
 8   Source               700 non-null    object
 9   Date of publication  699 non-null    object
 10  Link                 700 non-null    object
 11  Category             700 non-null    object
 12  Name(s) and age      697 non-null    object
 13  Occupation
Category  687 non-null    object
dtypes: float64(2), object(12)
memory usage: 76.8+ KB

In [20]:
# 2.remove unwanted columns
df = pd.read_csv("india_non-virus-deaths.csv")
df = df.drop(columns=['DB_LASTUPDATED_SET','Source','Date of publication','Link','Category'])
df

,S. No,Incident Location,District,State/UT,Date of incident,No. of deaths,Reason of death,Name(s) and age,Occupation\nCategory
0,1.0,Agra,Agra,Uttar Pradesh,"March 28,2020",1.0,"Exhaustion, Migration",Ranveer Singh (39),migrant worker- restaurant
1,2.0,Pandesara,Surat,Gujarat,"March 27, 2020",1.0,"Exhaustion, Lockdown",Gangaram(62),unspecified
2,3.0,Jaipur,Jaipur,Rajasthan,"March 29, 2020",1.0,"Walking, exhaustion, got sick",Sher Singh,migrant worker
3,4.0,Secunderabad,Secunderabad,Telangana,"April 1, 2020",1.0,"Exhaustion, Migration",Logesh Balasubramani (23),migrant worker
4,5.0,Mountainous peak over Jawahar Tunnel,Anantnag,Jammu and Kashmir,"March 31, 2020",3.0,"Buried under snow, Roadblock, Migration","Zubair Ahmed (18), Riyaz Ahmed (19), Ghulam Mo...",migrant worker
...,...,...,...,...,...,...,...,...,...
696,35.0,Kalenda,Mahasamund,Chhattisgarh,"June 2, 2020",1.0,"death at quarantine centre, unclear, death in ...",unspecified,unspecified
697,36.0,Gohrapadar,Gariaband,Chhattisgarh,"June 6, 2020",1.0,"suicide in quarantine centre, unclear",unspecified (20),migrant worker
698,37.0,Jayarampur,Balasore,Odisha,"June 30, 2020",1.0,"suicide in quarantine centre, unclear",unspecified (50),migrant worker
699,38.0,Dehradun,Dehradun,Uttarakhand,"June 12, 2020",1.0,"suicide in quarantine centre, unclear",unspecified (19),migrant worker
700,39.0,NaN,NaN,Chhattisgarh,May 21-June 4 2020,11.0,"deaths in quarantine centres, multiple reasons",NaN,NaN

In [21]:
#3. check count of unique

df.nunique()

S. No                   201
Incident Location       512
District                357
State/UT                 29
Date of incident        145
No. of deaths            14
Reason of death         348
Name(s) and age         638
Occupation\nCategory    190
dtype: int64

In [22]:
# 4.change types
df['No. of deaths'] = df['No. of deaths'].astype("Int64")
df['S. No'] =df['S. No'].astype("Int64")
df
df.info()
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   S. No                700 non-null    Int64
 1   Incident Location    556 non-null    object
 2   District             672 non-null    object
 3   State/UT             698 non-null    object
 4   Date of incident     694 non-null    object
 5   No. of deaths        700 non-null    Int64
 6   Reason of death      700 non-null    object
 7   Name(s) and age      697 non-null    object
 8   Occupation
Category  687 non-null    object
dtypes: Int64(2), object(7)
memory usage: 50.8+ KB

S. No                   201
Incident Location       512
District                357
State/UT                 29
Date of incident        145
No. of deaths            14
Reason of death         348
Name(s) and age         638
Occupation\nCategory    190
dtype: int64

In [23]:
# 5.set index
df = df.set_index('State/UT')
df

,S. No,Incident Location,District,Date of incident,No. of deaths,Reason of death,Name(s) and age,Occupation\nCategory
State/UT,,,,,,,,
Uttar Pradesh,1,Agra,Agra,"March 28,2020",1,"Exhaustion, Migration",Ranveer Singh (39),migrant worker- restaurant
Gujarat,2,Pandesara,Surat,"March 27, 2020",1,"Exhaustion, Lockdown",Gangaram(62),unspecified
Rajasthan,3,Jaipur,Jaipur,"March 29, 2020",1,"Walking, exhaustion, got sick",Sher Singh,migrant worker
Telangana,4,Secunderabad,Secunderabad,"April 1, 2020",1,"Exhaustion, Migration",Logesh Balasubramani (23),migrant worker
Jammu and Kashmir,5,Mountainous peak over Jawahar Tunnel,Anantnag,"March 31, 2020",3,"Buried under snow, Roadblock, Migration","Zubair Ahmed (18), Riyaz Ahmed (19), Ghulam Mo...",migrant worker
...,...,...,...,...,...,...,...,...
Chhattisgarh,35,Kalenda,Mahasamund,"June 2, 2020",1,"death at quarantine centre, unclear, death in ...",unspecified,unspecified
Chhattisgarh,36,Gohrapadar,Gariaband,"June 6, 2020",1,"suicide in quarantine centre, unclear",unspecified (20),migrant worker
Odisha,37,Jayarampur,Balasore,"June 30, 2020",1,"suicide in quarantine centre, unclear",unspecified (50),migrant worker
Uttarakhand,38,Dehradun,Dehradun,"June 12, 2020",1,"suicide in quarantine centre, unclear",unspecified (19),migrant worker
Chhattisgarh,39,NaN,NaN,May 21-June 4 2020,11,"deaths in quarantine centres, multiple reasons",NaN,NaN

In [29]:
# 6.sort values
df = df.sort_index()
df

,S. No,Incident Location,District,Date of incident,No. of deaths,Reason of death,Name(s) and age,Occupation\nCategory
State/UT,,,,,,,,
Delhi,14,Delhi,Delhi,"April 6, 2020",1,"Lockdown, Early discharge from hospital",Shahjahan (40),unspecified
Andhra Pradesh,28,different villages,Sangareddy,"March 31, 2020",4,"death, withdrawal",Mangali Ramulu(75); Lakshminarayana (30) Ramu ...,unspecified
Andhra Pradesh,15,Dundigal,Hyderbad,"March 31,2020",1,"Death, withdrawal",unspecified,unspecified
Andhra Pradesh,3,Chodavaram Block,Visakhapatnam,"March 31, 2020",1,Death by waiting in the sun,Mira Bi(65),unspecified
Andhra Pradesh,15,Mittapalle village,Chittoor,"April 28, 2020",1,"exhaustion, walking",Hari Prasad (26),migrant worker
...,...,...,...,...,...,...,...,...
West Bengal,187,"Regent Park, Kolkata",Kolkata,"June 30, 2020",2,"suicide, financial distress",unspecified (60); unspecified (40),small trader; unspecified
West Bengal,13,Talibpur,Birbhum,"April 4, 2020",1,died in clash,Sheikh Nasiruddin (40),unspecified
NaN,33,en route on train,NaN,"May 10-27, 2020",62,Shramik train deaths,See the source link,NaN
NaN,34,en route on train,NaN,unspecified,1,Shramik train death,Akhilesh,migrant worker- daily wage worker
NaN,<NA>,NaN,Deaths at Quarantine Centres,NaN,<NA>,NaN,NaN,NaN

In [30]:
# 7.checking duplicates
df[df.duplicated()]

Empty DataFrame
Columns: [S. No, Incident Location, District, Date of incident, No. of deaths, Reason of death, Name(s) and age, Occupation
Category]
Index: []

In [32]:
# # .check for no duplicates
df.duplicated().sum()

df.isnull()

np.int64(0)

In [34]:
# 8.re-load into excel
# firstly import openpyxl module in environment of anaconda navigator
import openpyxl
# to excel
df.to_excel("non_virus_deaths_cleaned.xlsx", index=True)

# to csv
df.to_csv("non_virus_deaths_cleaned.csv", index=True)